# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007pkg/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65vent.proto\x1a\x19google/protobuf/any.proto\"\xba\x06\n\rEventEnvelope\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12)\n\x08severity\x18\x03 \x01(\x0e\x32\x17.EventEnvelope.Severity\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12\x11\n\tuser_name\x18\x05 \x01(\t\x12\x18\n\x10source_component\x18\x06 \x01(\t\x12\x19\n\x11source_device_ref\x18\x07 \x01(\t\x12\x1a\n\x12source_device_name\x18\x08 \x01(\t\x12\x11\n\tsource_ip\x18\t \x01(\t\x12\x16\n\x0e\x64\x65stination_ip\x18\n \x01(\t\x12\x11\n\toperation\x18\x0b \x01(\t\x12\x11\n\tauditable\x18\x0c \x01(\x08\x12\x16\n\x0eresponse_state\x18\r \x01(\t\x12\x14\n\x0cresource_ref\x18\x0e \x01(\t\x12;\n\x0f\x63orrelation_ids\x18\x0f \x03(\x0b\x32\".EventEnvelope.CorrelationIdsEntry\x12\x39\n\x0eparameter_data\x18\x10 \x03(\x0b\x32!.EventEnvelope.ParameterDataEntry\x12;\n\x0f\x61\x64\x64itional_data\x18\x11 \x03(\x0b\x32\".EventEnvelope.AdditionalDataEntry\x1a\x35\n\x13\x43orrelationIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1aJ\n\x12ParameterDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x1aK\n\x13\x41\x64\x64itionalDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"[\n\x08Severity\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07VERBOSE\x10\x01\x12\x0f\n\x0bINFORMATION\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0c\n\x08\x43RITICAL\x10\x05\x42\tZ\x07pkg/apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_EVENTENVELOPE_SEVERITY = _descriptor.EnumDescriptor(
  name='Severity',
  full_name='EventEnvelope.Severity',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERBOSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFORMATION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=778,
  serialized_end=869,
)
_sym_db.RegisterEnumDescriptor(_EVENTENVELOPE_SEVERITY)


_EVENTENVELOPE_CORRELATIONIDSENTRY = _descriptor.Descriptor(
  name='CorrelationIdsEntry',
  full_name='EventEnvelope.CorrelationIdsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='EventEnvelope.CorrelationIdsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='EventEnvelope.CorrelationIdsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=623,
)

_EVENTENVELOPE_PARAMETERDATAENTRY = _descriptor.Descriptor(
  name='ParameterDataEntry',
  full_name='EventEnvelope.ParameterDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='EventEnvelope.ParameterDataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='EventEnvelope.ParameterDataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=699,
)

_EVENTENVELOPE_ADDITIONALDATAENTRY = _descriptor.Descriptor(
  name='AdditionalDataEntry',
  full_name='EventEnvelope.AdditionalDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='EventEnvelope.AdditionalDataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='EventEnvelope.AdditionalDataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=701,
  serialized_end=776,
)

_EVENTENVELOPE = _descriptor.Descriptor(
  name='EventEnvelope',
  full_name='EventEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='EventEnvelope.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='EventEnvelope.event_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='EventEnvelope.severity', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='EventEnvelope.event_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='EventEnvelope.user_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_component', full_name='EventEnvelope.source_component', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_device_ref', full_name='EventEnvelope.source_device_ref', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_device_name', full_name='EventEnvelope.source_device_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_ip', full_name='EventEnvelope.source_ip', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destination_ip', full_name='EventEnvelope.destination_ip', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='EventEnvelope.operation', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auditable', full_name='EventEnvelope.auditable', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_state', full_name='EventEnvelope.response_state', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_ref', full_name='EventEnvelope.resource_ref', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correlation_ids', full_name='EventEnvelope.correlation_ids', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameter_data', full_name='EventEnvelope.parameter_data', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='additional_data', full_name='EventEnvelope.additional_data', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENTENVELOPE_CORRELATIONIDSENTRY, _EVENTENVELOPE_PARAMETERDATAENTRY, _EVENTENVELOPE_ADDITIONALDATAENTRY, ],
  enum_types=[
    _EVENTENVELOPE_SEVERITY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=869,
)

_EVENTENVELOPE_CORRELATIONIDSENTRY.containing_type = _EVENTENVELOPE
_EVENTENVELOPE_PARAMETERDATAENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_EVENTENVELOPE_PARAMETERDATAENTRY.containing_type = _EVENTENVELOPE
_EVENTENVELOPE_ADDITIONALDATAENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_EVENTENVELOPE_ADDITIONALDATAENTRY.containing_type = _EVENTENVELOPE
_EVENTENVELOPE.fields_by_name['severity'].enum_type = _EVENTENVELOPE_SEVERITY
_EVENTENVELOPE.fields_by_name['correlation_ids'].message_type = _EVENTENVELOPE_CORRELATIONIDSENTRY
_EVENTENVELOPE.fields_by_name['parameter_data'].message_type = _EVENTENVELOPE_PARAMETERDATAENTRY
_EVENTENVELOPE.fields_by_name['additional_data'].message_type = _EVENTENVELOPE_ADDITIONALDATAENTRY
_EVENTENVELOPE_SEVERITY.containing_type = _EVENTENVELOPE
DESCRIPTOR.message_types_by_name['EventEnvelope'] = _EVENTENVELOPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventEnvelope = _reflection.GeneratedProtocolMessageType('EventEnvelope', (_message.Message,), {

  'CorrelationIdsEntry' : _reflection.GeneratedProtocolMessageType('CorrelationIdsEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENTENVELOPE_CORRELATIONIDSENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:EventEnvelope.CorrelationIdsEntry)
    })
  ,

  'ParameterDataEntry' : _reflection.GeneratedProtocolMessageType('ParameterDataEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENTENVELOPE_PARAMETERDATAENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:EventEnvelope.ParameterDataEntry)
    })
  ,

  'AdditionalDataEntry' : _reflection.GeneratedProtocolMessageType('AdditionalDataEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENTENVELOPE_ADDITIONALDATAENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:EventEnvelope.AdditionalDataEntry)
    })
  ,
  'DESCRIPTOR' : _EVENTENVELOPE,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:EventEnvelope)
  })
_sym_db.RegisterMessage(EventEnvelope)
_sym_db.RegisterMessage(EventEnvelope.CorrelationIdsEntry)
_sym_db.RegisterMessage(EventEnvelope.ParameterDataEntry)
_sym_db.RegisterMessage(EventEnvelope.AdditionalDataEntry)


DESCRIPTOR._options = None
_EVENTENVELOPE_CORRELATIONIDSENTRY._options = None
_EVENTENVELOPE_PARAMETERDATAENTRY._options = None
_EVENTENVELOPE_ADDITIONALDATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
